import React, { useState, useRef, FC } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faInstagram } from "@fortawesome/free-brands-svg-icons";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { auth } from "../firebas/initFirebase";

export const siteTitle = "GourmetApp";

export const Layout: FC = ({ children }) => {
  const [openHam, setOpenHam] = useState(false);
  const menuRef = useRef(null);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="og:title" content={siteTitle} />
      </Head>
      <header>
        <div className="header__box">
          <Link href="/">
            <a>
              <Image
                src="/image/logoTop.jpg"
                height={50}
                width={50}
                alt="icon"
              />
            </a>
          </Link>
          <h2>GourmetApp</h2>
          <nav>
            <ul>
              <li>
                <Link href="/">
                  <a className="header__boxLink">Home</a>
                </Link>
              </li>
              <li>
                <span className="header__boxLink">Category</span>
                <div className="header__hover">
                  <Link href="/all">
                    <a>
                      <span data-text="AllDishes">AllDishes</span>
                    </a>
                  </Link>
                  <Link href="/meat">
                    <a>
                      <span data-text="MeatDish">MeatDish</span>
                    </a>
                  </Link>
                  <Link href="/fish">
                    <a>
                      <span data-text="FishDish">FishDish</span>
                    </a>
                  </Link>
                  <Link href="/noodle">
                    <a>
                      <span data-text="Noodles">Noodles</span>
                    </a>
                  </Link>
                  <Link href="/salad">
                    <a>
                      <span data-text="Salad">Salad</span>
                    </a>
                  </Link>
                  <Link href="/dessert">
                    <a>
                      <span data-text="Dessert">Dessert</span>
                    </a>
                  </Link>
                  <Link href="/coffee">
                    <a>
                      <span data-text="Coffee">Coffee</span>
                    </a>
                  </Link>
                </div>
              </li>
              <li onClick={() => auth.signOut()}>
                <button>LogOut</button>
              </li>
              <li className="header__boxIi">
                <a
                  className="header__boxIcon"
                  href="https://www.instagram.com/gourmet126527/"
                >
                  <FontAwesomeIcon icon={faInstagram} />
                </a>
              </li>
            </ul>
          </nav>
          <div
            className={openHam ? "closeHum" : "header__boxSp"}
            onClick={() => setOpenHam(!openHam)}
            onBlur={() => setOpenHam(false)}
            ref={menuRef}
            tabIndex={0}
          >
            <span></span>
            <span></span>
            <span></span>
          </div>
          <div className={`hamMenu ${openHam ? "shown" : ""}`}>
            <Link href="/">
              <a>Home</a>
            </Link>
            <Link href="/all">
              <a>AllDishes</a>
            </Link>
            <Link href="/meat">
              <a>MeatDish</a>
            </Link>
            <Link href="/fish">
              <a>FishDish</a>
            </Link>
            <Link href="/noodle">
              <a>Noodles</a>
            </Link>
            <Link href="/salad">
              <a>Salad</a>
            </Link>
            <Link href="/dessert">
              <a>Dessert</a>
            </Link>
            <Link href="/coffee">
              <a>Coffee</a>
            </Link>
            <button onClick={() => auth.signOut()}>LogOut；</button>
            <a
              className="header__boxIcon"
              href="https://www.instagram.com/gourmet126527/"
            >
              <FontAwesomeIcon icon={faInstagram} />
            </a>
          </div>
        </div>
      </header>
      <main>{children}</main>
    </>
  );
};
