import React, { useState, useRef, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export const siteTitle = 'GourmetApp'

export default function Layout({children}) {
  const [openHam, setOpenHam] = useState(false);
  const menuRef = useRef(null);

  useEffect(() => {
    openHam && menuRef.current.focus();
  }, [openHam]);
  const onClickopenHam = () => () => {
    setOpenHam(!openHam);
  };

  return(
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="og:title" content={siteTitle} />
    </Head>
    <header>
      <div className="header__box">
        <Link href="/">
          <a>
            <Image
              src="/image/logo.JPG"
              height={50}
              width={50}
              alt="icon"
            />
          </a>
        </Link>
        <h2>GourmetApp</h2>
        <nav>
          <ul>
            <li>
              <Link href="/">
                <a>Home</a>
              </Link>
            </li>
            <li>
              <Link href="/all">
                <a>AllDishes</a>
              </Link>
            </li>
            <li>
              <Link href="/meat">
                <a>MeatDish</a>
              </Link>
            </li>
            <li>
              <Link href="/fish">
                <a>FishDish</a>
              </Link>
            </li>
            <li>
              <Link href="/noodle">
                <a>Noodles</a>
              </Link>
            </li>
            <li>
              <Link href="/salad">
                <a>Salad</a>
              </Link>
            </li>
            <li>
              <Link href="/dessert">
                <a>Dessert</a>
              </Link>
            </li>
            <li>
              <Link href="/coffee">
                <a>Coffee</a>
              </Link>
            </li>
          </ul>
        </nav>
        <div 
          className={openHam ? 'closeHum' : 'header__boxSp'} 
          onClick={() => setOpenHam(!openHam)} 
          onBlur={() => setOpenHam(false)} 
          ref={menuRef} 
          tabIndex={0}
        > 
          <span></span>
          <span></span>
          <span></span>
        </div>
        <div className={`hamMenu ${openHam ? 'shown' : ''}`}>
          <Link href="/">
            <a onClick={onClickopenHam()}>Home</a>
          </Link>
          <Link href="/all">
            <a onClick={onClickopenHam()}>AllDishes</a>
          </Link>
          <Link href="/meat">
            <a onClick={onClickopenHam()}>MeatDish</a>
          </Link>
          <Link href="/fish">
            <a onClick={onClickopenHam()}>FishDish</a>
          </Link>
          <Link href="/noodle">
            <a onClick={onClickopenHam()}>Noodles</a>
          </Link>
          <Link href="/salad">
            <a onClick={onClickopenHam()}>Salad</a>
          </Link>
          <Link href="/dessert">
            <a onClick={onClickopenHam()}>Dessert</a>
          </Link>
          <Link href="/coffee">
            <a onClick={onClickopenHam()}>Coffee</a>
          </Link>
        </div>
      </div>
    </header>
    <main>{children}</main>
    </>
  )
}